baseURL = 'http://bruce.wsl/'
languageCode = 'en-us'
title = "Bruce's Hugo Site"
theme = 'kraiklyn_moved'

[[menu.shortcuts]]
name = "See it on Github"
url = "https://github.com/bcgwebdesign/timetable"
weight = 20
