baseURL = 'https://bcgwebdesign.github.io/timetable/'
languageCode = 'en-us'
title = 'Bruce Hugo Site'
theme = 'kraiklyn_moved'

[[menu.shortcuts]]
name = "See it on Github"
url = "https://github.com/bcgwebdesign/timetable"
weight = 20
