baseURL = 'https://bcgwebdesign.github.io/timetable/'
languageCode = 'en-us'
title = 'Bruce Hugo Site'
theme = 'kraiklyn_moved'

[[menu.shortcuts]]
name = "Javascript API"
url = "https://docs.surfly.com/javascript.html"
weight = 20
